### PR TITLE
Implement verify function

### PR DESCRIPTION
**Pull request by huming2207**
Hi @Yatekii 

This PR implements the `Verify()` function mentioned in this issue: https://github.com/probe-rs/flash-algorithm-template/issues/5

I haven't tested that but it should work, so I've created a draft PR first. 

Regards,
Jackson Hu

### CODE REVIEW

**Comment by huming2207** [comment]
I think I've got no more to commit here, please go ahead to review. Thanks.

**Comment by huming2207** [comment]
Any updates?

**Review by Yatekii — APPROVED** [review]
Sorry it took so long ...

**Comment by huming2207** [comment]
all good, thanks for the review!

**Pull request merged**
